// Generated by tools/gen_rds_golden.py -- do not edit; re-run the script.
// seed=1 groups=10 lead=37 tail=4 rds_peak=0.03 rds_phase=0.0 noise_lsb=0.0 lpf=butter2@2500Hz lock_run=3
localparam int N_IN       = 218500;
localparam int N_S0       = 43700;
localparam int N_S1       = 43700;
localparam int N_S2       = 43700;
localparam int N_SYM      = 1081;   // symbols emitted by the NCO (S3 items)
localparam int N_BIT      = 1081;   // == N_SYM: one data bit per symbol
localparam int N_BLK      = 38;
localparam int SYM_SKIP   = 2;   // first symbol whose hard decision is checked
localparam int SYM_END    = 1081;   // one past the last symbol whose hard decision is checked
localparam int S5_FROM    = 27;   // first bit index whose 26-bit window lies fully in the checked range
localparam int TOL_S1     = 4;
localparam int TOL_S3     = 164;
localparam int SLACK_S0   = 0;
localparam int SLACK_S1   = 2;
localparam int SLACK_S2   = 2;
localparam int SLACK_S3   = 2;
localparam int SLACK_S4   = 2;
localparam int SLACK_S5   = 2;
localparam int SLACK_S6   = 2;
localparam int SLACK_S7   = 1;
localparam logic [31:0] NCO_STEP   = 32'h06555555;
localparam logic [31:0] NCO_PHASE0 = 32'hB6C00000;
localparam int LOCK_RUN   = 3;
localparam logic [15:0]  EXP_PI = 16'h5A5A;
localparam logic [63:0]  EXP_PS = 64'h464D474F4C44454E;   // char 0 in [63:56]
localparam logic [511:0] EXP_RT = 512'h474F4C44454E20524453205445535421000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;   // char 0 in [511:504], unseen = 0x00
